### ISSUE TITLE
$script:SafeCommands is null in the finally block of the Decribe function.

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/psl-pester#11]
When an exception is thrown from AfterAll or AfterEach, $SafeCommands does not appear to be in scope and an unhandled exception is thrown in the finally block for Describe.   The result is $Pester.LeaveDescribe() is never called and subsequent tests fail due to nested Describe blocks.

The symptom is an a test failure followed by another a reported failure
 [-] Error occurred in Describe block 339ms
   Cannot index into a null array.
Subsequent tests start failing due to nested Describe blocks.
The null array is caused by the statement `$SafeCommands['Select-Object']`
Adding an arbitrary reference to $SafeCommands earlier in the function result in the same null array reference.

Note that it's not clear at this point if it is an error in pester or in PowerShell.

**Comment by dlwyatt** [comment]
This is very odd.  SafeCommands exists in the script scope of the Pester module, and is populated when the module loads; it should never be null or undefined.
